const users = [{"id":1,"first_name":"Johan","last_name":"Novic","email":"jnovic0@csmonitor.com","gender":"Male"},
{"id":2,"first_name":"Bryn","last_name":"Reisin","email":"breisin1@weebly.com","gender":"Male"},
{"id":3,"first_name":"Gertrudis","last_name":"Mariet","email":"gmariet2@nsw.gov.au","gender":"Female"},
{"id":4,"first_name":"Michele","last_name":"MacKibbon","email":"mmackibbon3@google.com.hk","gender":"Female"},
{"id":5,"first_name":"Herman","last_name":"Butts","email":"hbutts4@homestead.com","gender":"Male"},
{"id":6,"first_name":"Amanda","last_name":"Caple","email":"acaple5@google.de","gender":"Female"},
{"id":7,"first_name":"Alick","last_name":"Garnall","email":"agarnall6@about.com","gender":"Male"},
{"id":8,"first_name":"Daven","last_name":"Hakes","email":"dhakes7@wordpress.com","gender":"Male"},
{"id":9,"first_name":"Melisent","last_name":"Perigeaux","email":"mperigeaux8@uol.com.br","gender":"Female"},
{"id":10,"first_name":"Kellen","last_name":"Edgecombe","email":"kedgecombe9@t-online.de","gender":"Male"},
{"id":11,"first_name":"Elenore","last_name":"MacCurtain","email":"emaccurtaina@blogtalkradio.com","gender":"Bigender"},
{"id":12,"first_name":"Pearl","last_name":"Anselmi","email":"panselmib@illinois.edu","gender":"Female"},
{"id":13,"first_name":"Farra","last_name":"McCloughlin","email":"fmccloughlinc@skyrock.com","gender":"Female"},
{"id":14,"first_name":"Wilhelm","last_name":"Aire","email":"waired@umn.edu","gender":"Male"},
{"id":15,"first_name":"Lenard","last_name":"Turban","email":"lturbane@fc2.com","gender":"Male"},
{"id":16,"first_name":"Kristan","last_name":"Tinline","email":"ktinlinef@springer.com","gender":"Female"},
{"id":17,"first_name":"Gelya","last_name":"Jakubovits","email":"gjakubovitsg@narod.ru","gender":"Female"},
{"id":18,"first_name":"Clyve","last_name":"Baskeyfield","email":"cbaskeyfieldh@examiner.com","gender":"Male"},
{"id":19,"first_name":"Roobbie","last_name":"Petegre","email":"rpetegrei@globo.com","gender":"Female"},
{"id":20,"first_name":"Cally","last_name":"Hunnybun","email":"chunnybunj@usatoday.com","gender":"Female"},
{"id":21,"first_name":"Bernadine","last_name":"Hacking","email":"bhackingk@craigslist.org","gender":"Female"},
{"id":22,"first_name":"Tressa","last_name":"Jaskiewicz","email":"tjaskiewiczl@mozilla.com","gender":"Female"},
{"id":23,"first_name":"Danni","last_name":"MacEnelly","email":"dmacenellym@google.it","gender":"Female"},
{"id":24,"first_name":"Joline","last_name":"Whear","email":"jwhearn@macromedia.com","gender":"Female"},
{"id":25,"first_name":"Hamlin","last_name":"Daintier","email":"hdaintiero@angelfire.com","gender":"Male"},
{"id":26,"first_name":"Everard","last_name":"Reskelly","email":"ereskellyp@home.pl","gender":"Male"},
{"id":27,"first_name":"Nady","last_name":"Fumagallo","email":"nfumagalloq@ovh.net","gender":"Female"},
{"id":28,"first_name":"Shandie","last_name":"Mardling","email":"smardlingr@ihg.com","gender":"Female"},
{"id":29,"first_name":"Clevey","last_name":"Newis","email":"cnewiss@chicagotribune.com","gender":"Male"},
{"id":30,"first_name":"Verla","last_name":"Zorzin","email":"vzorzint@army.mil","gender":"Female"},
{"id":31,"first_name":"Naomi","last_name":"Burder","email":"nburderu@toplist.cz","gender":"Female"},
{"id":32,"first_name":"Marchall","last_name":"Tourville","email":"mtourvillev@forbes.com","gender":"Male"},
{"id":33,"first_name":"Timothy","last_name":"Romanini","email":"tromaniniw@fc2.com","gender":"Male"},
{"id":34,"first_name":"Keir","last_name":"Saxon","email":"ksaxonx@newyorker.com","gender":"Male"},
{"id":35,"first_name":"Ezequiel","last_name":"Foldes","email":"efoldesy@youtu.be","gender":"Male"},
{"id":36,"first_name":"Zuzana","last_name":"Keningley","email":"zkeningleyz@bbc.co.uk","gender":"Female"},
{"id":37,"first_name":"Teena","last_name":"Cowerd","email":"tcowerd10@ezinearticles.com","gender":"Female"},
{"id":38,"first_name":"Neale","last_name":"World","email":"nworld11@wunderground.com","gender":"Male"},
{"id":39,"first_name":"Bryce","last_name":"Lindeman","email":"blindeman12@qq.com","gender":"Male"},
{"id":40,"first_name":"Deane","last_name":"Pattington","email":"dpattington13@chicagotribune.com","gender":"Female"},
{"id":41,"first_name":"Sinclare","last_name":"Saby","email":"ssaby14@bigcartel.com","gender":"Male"},
{"id":42,"first_name":"Pren","last_name":"Jossel","email":"pjossel15@behance.net","gender":"Male"},
{"id":43,"first_name":"Hewett","last_name":"Bartholomaus","email":"hbartholomaus16@twitter.com","gender":"Agender"},
{"id":44,"first_name":"Henka","last_name":"Gagin","email":"hgagin17@ow.ly","gender":"Female"},
{"id":45,"first_name":"Wendall","last_name":"Dickins","email":"wdickins18@nature.com","gender":"Male"},
{"id":46,"first_name":"Ariadne","last_name":"Shelborne","email":"ashelborne19@furl.net","gender":"Female"},
{"id":47,"first_name":"Bern","last_name":"Rustedge","email":"brustedge1a@google.com.hk","gender":"Male"},
{"id":48,"first_name":"Janos","last_name":"Emmet","email":"jemmet1b@spiegel.de","gender":"Male"},
{"id":49,"first_name":"Fletcher","last_name":"Follos","email":"ffollos1c@fda.gov","gender":"Male"},
{"id":50,"first_name":"Adolf","last_name":"de Keep","email":"adekeep1d@archive.org","gender":"Male"}]

export const getUsers = function(){
    return users;
}