// import { CHANGE_BUTTON_LOCK_STATUS, CHANGE_PAUSE_STATUS, CURRENT_GRID_UPDATE, DELETE_ACTION_HISTORY, FORM_THE_GAME_PATTERN, GRID_UPDATE, INCREASE_MISTAKE_COUNT, INSERT_ACTION_HISTORY, SELECTED_BUTTON_UPDATE, UPDATE_ASYNCSTORAGE_FOR_NEW_GAME, UPDATE_FROM_LAST_PLAYED_GAME, UPDATE_REMAINING_NUMS_LIST, UPDATE_SELECTED_SMALL_SQUARE_INDEX, UPDATE_USER_INFO } from "../Types";
import AsyncStorage from '@react-native-async-storage/async-storage'

export const updateUserInfo = (info)=>{
    return{
      type:UPDATE_USER_INFO,
      userInfo:info
    }
  }
